### ISSUE TITLE
About the evaluation method for occlusion orientation map ?

### ISSUE THREAD

**Issue by yuzhegao** [GuoxiaWang/DOOBNet#5]
Hi ! Guoxia Wang,
  I had read the evaluation matlab code, which include the evaluation method of **edge** and **occlusion orientation**. And I found that the part of occlusion orientation eval is a little confused. Here is some piece of code in doobscript/evaluation/collect_eval_bdry_occ.m

![image](https://user-images.githubusercontent.com/35888464/56136209-eb743100-5fc4-11e9-85f8-33542cd7e7ec.png)

So from the code above, the **AA_edge** tranfer to func:collect_eval_bdry_v2 for edge evaluation, and **AA_ori** for occlusion orientation evaluation. but just as the annotation I add above, the AA_ori consist of [thresh  cntR sumR cntP_occ sumP ], so why using the edge result cntR and sumR here?（I mean, use edge result in orientation eval）; This maybe not proper, and if I eval the result in this way, the orientation result will be influenced by edge result (when the edge result is improve, the orientation result will be improve too)

Besides, in orientation predict task, there is no positive and negative (different from edge task), so it's hard to calculate the "recall" and "precision" as edge task. Why not use the **precision** to eval the result of orientation map? 

Really Thanks for your answer !

**Comment by GuoxiaWang** [comment]
@yuzhegao 

Hi,  yuzhegao.

For the first question, you can refer Sec. 5.1 of  [DOOBNet](https://arxiv.org/pdf/1806.03772.pdf) paper, where I state why we use OPR criteria. We model the object occlusion boundary detection as unified conditional problem. Let A be the probability of Object Occlusion Boundary,  B be the probability of  Object Boundary,  C be the probability of Occlution Orientation, so P(A) = P(C|B). Because of the occlusion relationships estimation relies on object boundaries,  if you haswrong object boundaries estimation, the occlusion orientation has no sense.

Question 2, you can refer Sec. 5.1 of [DOC](https://arxiv.org/pdf/1511.06457.pdf) paper. The occlusion relationship only have 2 possibilities on the object boundary.

Thank you for your reading.

**Comment by yuzhegao** [comment]
@GuoxiaWang
Really Thanks！And one more question，I had just found that DOOBNet use **label_edge** as the weight of OrientationSmoothL1Loss, so here just calculate the loss on the edge pixel.  Maybe the loss of non-edge pixel is also useful. So why not using a class-balance weight instead of this binary weight（the label edge
）?
Sorry for bother you so many times.

**Comment by GuoxiaWang** [comment]
@yuzhegao 
Because P(A) = P(C|B), labe_edge as the weight of OrientationSmoothL1Loss as it is the orientation mask.
